# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OverflightContourCalculator
                                 A QGIS plugin
 Calculates aircraft overflight contours and other metrics based on CAA CAP 1498.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-30
        copyright            : (C) 2026 by Leevi Miettinen
        email                : leevi.miettinen@finavia.fi
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OverflightContourCalculator class from file OverflightContourCalculator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .overflight_contour_calculator import OverflightContourCalculator
    return OverflightContourCalculator(iface)
